@sc.js.JSSettings(jsLibFiles="js/javasys.js", prefixAlias="jv_")
Enum {
   // Because valueOf not defined on java.lang.Enum, but instead generated by the compiler we define this annotation
   // in EnumDeclaration's valueOfMethod field - a dummy method defined to represent the generated method
   //override @sc.js.JSMethodSettings(replaceWith="_valueOf") valueOf(String name);
}
